server:
  port: 8090

info:
  artifactId: "${project.name}"
  version: "${project.version}"

spring:
  application:
    name: Financial-Service
  datasource:
    url: jdbc:mysql://localhost:3306/financial?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: '12345678'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  key: ymLTU8rq83j4fmJZj60wh4OrMNuntIj4fmJ